# Generated by Django 4.2.2 on 2023-08-29 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNum', models.IntegerField()),
                ('mmr', models.IntegerField()),
                ('nickname', models.CharField(max_length=90)),
                ('rank', models.IntegerField()),
                ('totalGames', models.IntegerField()),
                ('winrate', models.DecimalField(decimal_places=1, max_digits=6)),
                ('averageKills', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamenumber', models.IntegerField()),
                ('character', models.IntegerField()),
                ('beforemmr', models.IntegerField()),
                ('aftermmr', models.IntegerField()),
                ('gamerank', models.IntegerField()),
                ('playerkill', models.IntegerField()),
                ('playerAss', models.IntegerField()),
                ('mosterkill', models.IntegerField()),
                ('startDtm', models.DateTimeField()),
                ('mmrGain', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerecord.gameuser')),
            ],
        ),
    ]
