# Generated by Django 4.2.2 on 2023-08-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNum', models.IntegerField()),
                ('mmr', models.IntegerField()),
                ('nickname', models.CharField(max_length=90)),
                ('rank', models.IntegerField()),
                ('totalGames', models.IntegerField()),
                ('winrate', models.DecimalField(decimal_places=1, max_digits=6)),
                ('averageKills', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
