# Generated by Django 4.2.2 on 2023-09-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='updatedate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
