# Generated by Django 4.2.2 on 2023-09-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0002_gameuser_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
