# Generated by Django 4.2.2 on 2023-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerecord', '0003_alter_gameuser_updatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='damageToMonster',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='damageToPlayer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='premaid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='useConsole',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='useWard',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
