# Generated by Django 4.2.2 on 2023-08-23 08:07

from django.db import migrations, models
import django.db.models.deletion
import todo.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_user', models.CharField(max_length=80)),
                ('team', models.CharField(choices=[('경영팀', '경영팀'), ('고객대응팀', '고객대응팀'), ('기술지원팀', '기술지원팀'), ('전략기획팀', '전략기획팀'), ('소속없음', '소속없음')], max_length=80)),
                ('title', models.CharField(max_length=80, validators=[todo.validators.validate_test])),
                ('content', models.CharField(max_length=80)),
                ('is_complete', models.BooleanField(default=False)),
                ('compleated_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('subchoic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(blank=True, choices=[('경영팀', '경영팀'), ('고객대응팀', '고객대응팀'), ('기술지원팀', '기술지원팀'), ('전략기획팀', '전략기획팀'), ('소속없음', '소속없음')], max_length=80, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('compleated_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo.task')),
            ],
        ),
    ]
