# Generated by Django 4.2.2 on 2023-08-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('attack', models.DecimalField(decimal_places=1, max_digits=6)),
                ('hp', models.DecimalField(decimal_places=1, max_digits=6)),
                ('hpregen', models.DecimalField(decimal_places=1, max_digits=6)),
                ('stamina', models.DecimalField(decimal_places=1, max_digits=6)),
                ('stregen', models.DecimalField(decimal_places=1, max_digits=6)),
                ('defense', models.DecimalField(decimal_places=1, max_digits=6)),
                ('atkspeed', models.DecimalField(decimal_places=1, max_digits=6)),
                ('speed', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
    ]
