# Generated by Django 4.2.2 on 2023-09-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_character_koreanname'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='RPeff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='character',
            name='RPfor7days',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='trygame7days',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
